attakei/sphinx-revealjs

sphinx_revealjs/themes/sphinx_revealjs/page.html
tests/test_it.py

Remove tag that resource is not exits

---

demo/revealjs4/example-background-only-section.rst
demo/revealjs4/index.rst

Thanks a lot for the great extension!
The demo example is helpful and I noticed some typos.
I noticed them using the VSCode extension, [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

Fix typo in demo examples

---

tests/test_conf.py

- Rename testcase function to fix duplicate
- Update test to align for current reveal.js

Fix test cases for #42

---

demo/revealjs4/conf.py
demo/revealjs4/index.rst
sphinx_revealjs/__init__.py

Inherit custom nodes of other extensions

---

docs/configurations.rst
sphinx_revealjs/__init__.py
sphinx_revealjs/builders.py
tests/test_conf.py

Add directive revealjs_js_files

---

package-lock.json
package.json

Update Reveal.js version

---

.github/workflows/continuous-integration.yml
poetry.lock
pyproject.toml
tests/test_conf.py
tests/test_demo_revealjs4.py
tests/test_directives.py
tests/test_revealjs_fragments.py
tests/test_revealjs_slide.py

To specify supporting python and sphinx versions, run unittests by CI

Follow up multiple python and sphinx versions

---

package-lock.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/4.2.1)

Update reveal.js from v4.2.0 to 4.2.1

---

package-lock.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/4.3.1)

Update reveal.js from v4.3.0 to 4.3.1

---

package-lock.json
package.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/4.3.1)

Update reveal.js from v4.3.1 to 4.3.1

---

doc/setup.rst
sphinx_revealjs/__init__.py
sphinx_revealjs/builders.py
tests/test_demo_revealjs4.py

Adding `dirrevealjs` builder

---

sphinx_revealjs/themes/sphinx_revealjs/page.html

fix: Add role for searchable by sphinx

---

sphinx_revealjs/__init__.py
tests/roots/test-misc/has-break.rst
tests/test_directives.py

Fix behavior of custom directives in dirrevealjs builder

---

CHANGES-2.x.rst
doc/configurations.rst
doc/upgrade/2.x.rst
sphinx_revealjs/__init__.py
sphinx_revealjs/builders.py
tests/roots/test-default/conf.py
tests/roots/test-for-commented-notes/conf.py
tests/roots/test-for-config/conf.py
tests/test_configurations/test_generatings.py
tests/test_generatings.py

Remove func for generating needless pages

---

sphinx_revealjs/directives.py

Add data-XXX attributes for section elements of revealjs

---

sphinx_revealjs/__init__.py
tests/test_other_builders.py

Add handler functions for all nodes to any builders(sphinx-bundled)

---

demo/_sass/custom.scss
demo/_sections/interactive-content.rst
doc/directives.rst
npm-shrinkwrap.json
package.json
sphinx_revealjs/directives.py
tests/roots/test-default/with-revealjs-fragments.rst
tests/test_directives/test_fragments.py

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/4.5.0)

Update reveal.js from v4.4.0 to 4.5.0

---

demo/_sections/standard-usage.rst
demo/conf.py
doc/optional-extensions/footnotes.rst
sphinx_revealjs/__init__.py
sphinx_revealjs/builders.py
sphinx_revealjs/ext/footnotes/__init__.py
sphinx_revealjs/ext/footnotes/static/sphinx-revealjs/css/footnotes.css
sphinx_revealjs/ext/footnotes/static/sphinx-revealjs/css/footnotes.css_t
tests/roots/test-default/with-footnotes.rst
tests/test_extensions/test_footnotes.py

Add optional-extension `sphinx_revealjs.ext.footnotes`

---

npm-shrinkwrap.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/5.0.2)

Update reveal.js from v5.0.2 to 5.0.2

---

CHANGELOG.rst
demo/_sections/using-plugins.rst
demo/conf.py
doc/configurations.rst
doc/tips/create-custom-theme.rst
doc/tips/customizing-design-simply.rst
doc/upgrade/3.x.rst
pyproject.toml
sphinx_revealjs/__init__.py
sphinx_revealjs/contexts.py
sphinx_revealjs/themes/__init__.py
tests/test_configurations/test_complex_variables.py
tests/test_configurations/test_scripts.py
tests/test_configurations/test_theme.py
tests/test_generatings.py
tests/test_theme.py
tools/fetch_revealjs.py

Change path of bundled revealjs 

---

CHANGELOG.rst

Congrats v3 release 🎉
This is a pull request to fix typo in changelog
ref: https://sphinx-revealjs.readthedocs.io/en/latest/directives/#directive-revealjs-section

Fix typo v3 changelog

---

npm-shrinkwrap.json
package.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/5.1.0)

Update reveal.js from v5.0.5 to 5.1.0

---

sphinx_revealjs/themes/revealjs-simple/page.html
tests/roots/test-simple-theme/conf.py
tests/roots/test-simple-theme/index.rst
tests/test_theme.py

fix: Append metatags

---

sphinx_revealjs/__init__.py
sphinx_revealjs/deprecated.py

This is to manage deprecated messages on module.
And used to drop Sphinx 4.x supports.
Refs: #167

feat: Manage deprecated by modules

---

npm-shrinkwrap.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/5.1.0)

Update reveal.js from v5.1.0 to 5.1.0

---

npm-shrinkwrap.json
package.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/5.2.0)

Update reveal.js from v5.1.0 to 5.2.0

---

pyproject.toml

refactor: Migrate deps correctly

---

demo/conf.py
doc/optional-extensions/oembed.rst
sphinx_revealjs/ext/oembed.py
tests/roots/test-oembed/conf.py
tests/roots/test-oembed/index.rst
tests/roots/test-oembed/with-directive.rst
tests/test_extensions/test_oembed.py

Implement oEmbed optional extension
