attakei/sphinx-revealjs

sphinx_revealjs/writers.py

Attributes for `.. revealjs_section::` doesn't work on first section of a group. For example, `data-background-color` doesn't work on the first slide, the title one.
Also when you set a `data-background-color` under header level 2, the background apply to the bounding `<section>`, so all sub sections get this background color.
Now, attributes are set to the first no-bounding `<section>`. So `data-background-color` works on the title slide and it applies on the header level 2 slides.

Allow to have attr on first `<section>` elements.

---

docs/configurations.rst
docs/customize_sections.rst
docs/index.rst
docs/migrations.rst

I noticed some typos using the VSCode extension, [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).
~I fixed a few things, but docs has a lot of files.
Sorry, I don't think I've covered them all right now.~
~I don't mind if you merge this, but I'll check the rest typo later.~
(updated) I checked the rest of rst files under the docs directory with the spell checker.

Fix typo in docs

---

tests/test_demo_revealjs4.py
tests/test_revealjs_fragments.py
tests/test_revealjs_slide.py
tests/testutils.py

I noticed some typos in test codes with VSCode [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension

fix typo under tests directory

---

sphinx_revealjs/builders.py
tests/test_conf.py

Resolve https://github.com/attakei/sphinx-revealjs/issues/40
Theme CSS comes before user-defined CSS for users to overwrite some properties defined in theme CSS with their own CSS

Theme CSS now comes before user-defined CSS in the head tag

---

sphinx_revealjs/writers.py

This change includes the section id in the presentation to allow adding custom css and allowing fixed urls to a slide. For example the following slide:
```rst
My Section
=========
```
It has the id "my-section". The next slide:
```rst
.. _other-section:
Other slide
=========
```
It has the id "other-section". Thanks to this change the slides can be linked:
https://nekmo.github.io/django-rest-framework-presentacion/#/baterias-incluidas
And add custom css:
https://github.com/Nekmo/django-rest-framework-presentacion/blob/presentation/index.html#L100-L105
https://github.com/Nekmo/django-rest-framework-presentacion/blob/master/_static/theme.scss#L253-L258

Add id to slide sections.

---

docs/configurations.rst
sphinx_revealjs/__init__.py
sphinx_revealjs/writers.py
tests/test_conf.py

This PR is to fix and update features about using ids as internal link.
(Base idea is #59 )
All internal links are used `id` labels forcefully.
User cannot use numbered links then lost back compatibility.
This feature must be provided as optional.
Are there users that want to mixed style links.
- Default is numbered links
- If label is exists, use string links for only this section

Handle section id as reveal.js internal link

---

package-lock.json
package.json
tools/fetch_revealjs.py

For #67 .
But, fetch process does not work because there is not reveal.js v4.1.3 in GitHub releases.
Merge this PR after updated it.

Update reveal.js version ( to 4.1.3)

---

CHANGES.rst
demo/revealjs4/conf.py
docs/configurations.rst
sphinx_revealjs/contexts.py
tests/test_conf.py

Update about issue #56.
In version 1.x , `revealjs_script_conf` accepts `str` and `dict`(JSON serializable) types.

Update behavior of `revealjs_script_conf`

---

sphinx_revealjs/__init__.py
sphinx_revealjs/builders.py
tests/test_conf.py

- Split `html_js_files` and `revealjs_js_files` to configure per any builders.
- Does not add js files that need not use as reveal.js (fix #25)

Split `html_js_files` and `revealjs_js_files`

---

doc/configurations.rst

I noticed some typos about `revealjs_script_plugins`.
Please merge this.

Fix typos in doc/configurations.rst

---

.github/workflows/main.yml
sphinx_revealjs/builders.py

Fix to support Sphinx 5.0.x with #124

fix: Initialize of builders accepts app and env for Sphinx>5.1

---

demo/revealjs4/_locales/ja/LC_MESSAGES/main.po

Thank you for all your awesome library.
I found double backquotes appearing on demo slide.
https://attakei.github.io/sphinx-revealjs/main-ja.html
So I send this pull request😃
But I am not experienced in Sphinx translation, so I may have changed the file improperly.
I noticed that English slide uses **single** backquote.
https://attakei.github.io/sphinx-revealjs/main-en.html
So maybe it should be as follows (single backquote version)
```
msgstr "`revealjs-section` や `revealjs-break` を用いてアニメーションの設定が可能です。"
```

doc: fix double backquotes appearing on demo slide

---

tests/roots/test-default/conf.py
tests/roots/test-for-commented-notes/conf.py

The test code was very helpful in writing tests for the Sphinx extension.
Thank you very much!
I found a typo in conf.py so send this pull request.
"For-commented-notes" case may require modification of the docstring itself.

Fix typo in conf.py for test data

---

npm-shrinkwrap.json
package.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/4.6.1)

Update reveal.js from v4.5.0 to 4.6.1

---

npm-shrinkwrap.json
package.json

Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/5.0.4)

Update reveal.js from v5.0.2 to 5.0.4

---

sphinx_revealjs/writers.py
tests/roots/test-default/with-revealjs-break-decorated.rst
tests/test_directives/test_break.py

Render all nodes in parent heading by `revealjs-break`

---

sphinx_revealjs/directives.py

fix: Keep known attributes of `docutils.nodes.Element`

---

sphinx_revealjs/directives.py
sphinx_revealjs/writers.py
tests/roots/test-default/with-section-directives/with-break-background-iframe-local.rst
tests/roots/test-default/with-section-directives/with-vertical-background-iframe-local.rst
tests/test_directives/test_section.py

This fixes include `revealjs_vertical` and `revealjs_break`.
Refs: #184

Fix/copy data background assets (2)

---

npm-shrinkwrap.json
package.json

Reverts attakei/sphinx-revealjs#200
Due: This commit cannot build demo.

Revert "Update reveal.js from v5.1.0 to 5.2.0"

---

demo/_static/.gitignore
demo/conf.py
doc/conf.py
doc/optional-extensions/sass.rst
pyproject.toml
sphinx_revealjs/ext/sass/.gitignore
sphinx_revealjs/ext/sass/__init__.py
sphinx_revealjs/ext/sass/dart_sass.py
tests/roots/test-sass/_static/style.scss
tests/roots/test-sass/_static/style2.scss
tests/roots/test-sass/conf.py
tests/roots/test-sass/index.rst
tests/test_extensions/test_sass.py
uv.lock

This PR is to create optional extension `sphinx_revealjs.ext.sass` that compile scss/sass for Revealjs theme.
Reveal.js 5.2.0 uses [`sass:color`](https://sass-lang.com/documentation/modules/color/) module in theme,
but libsass [^1] is not supported.
Therefore, it should use dart-sass to compile custom theme.
Currently:
- [dart-sass](https://pypi.org/project/dart-sass/) is published on PyPI, but it is old and stopped maintenance.
- I managed [atsphinx-toybox](https://pypi.org/project/atsphinx-toybox/) that includes sass extension, but it has too many features to use sass.
New optional extension will provide sass compiler optimized revealjs themes.
- Set theme sass directory into loading paths in default.
- Keep compatibility parameters for `sphinxcontrib-sass` (for users included me). …

Define new sub-extension to compile sass/scss
